// <auto-generated />
using System;
using ClyvoDayApiDocker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ClyvoDayApiDocker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClyvoDayApiDocker.Models.AnimalEstimacao", b =>
                {
                    b.Property<int>("AnimalEstimacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalEstimacaoId"));

                    b.Property<int>("Age")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("TutoresId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("TutoresId1")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)");

                    b.HasKey("AnimalEstimacaoId");

                    b.HasIndex("TutoresId");

                    b.HasIndex("TutoresId1");

                    b.ToTable("AnimaisEstimacao");
                });

            modelBuilder.Entity("ClyvoDayApiDocker.Models.Clinica", b =>
                {
                    b.Property<int>("ClinicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClinicaId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ClinicaId");

                    b.ToTable("Clinicas");
                });

            modelBuilder.Entity("ClyvoDayApiDocker.Models.EventoCuidado", b =>
                {
                    b.Property<int>("EventoCuidadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventoCuidadoId"));

                    b.Property<int>("AnimalEstimacaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("EventCompleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TypeEvent")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("EventoCuidadoId");

                    b.HasIndex("AnimalEstimacaoId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("ClyvoDayApiDocker.Models.MonitoramentoAnimal", b =>
                {
                    b.Property<int>("MonitoramentoAnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonitoramentoAnimalId"));

                    b.Property<int>("AnimalEstimacaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("EnergyLevel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Food")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Medication")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime>("MonitoringDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RecentActivities")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SleepQuality")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("MonitoramentoAnimalId");

                    b.HasIndex("AnimalEstimacaoId");

                    b.ToTable("Monitoramentos");
                });

            modelBuilder.Entity("ClyvoDayApiDocker.Models.Tutores", b =>
                {
                    b.Property<int>("TutoresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutoresId"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ScoreEngagement")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("TutoresId");

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("ClyvoDayApiDocker.Models.Veterinario", b =>
                {
                    b.Property<int>("VeterinarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeterinarioId"));

                    b.Property<int>("ClinicaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Crmv")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("VeterinarioId");

                    b.HasIndex("ClinicaId");

                    b.ToTable("Veterinarios");
                });

            modelBuilder.Entity("ClyvoDayApiDocker.Models.AnimalEstimacao", b =>
                {
                    b.HasOne("ClyvoDayApiDocker.Models.Tutores", null)
                        .WithMany("AnimaisEstimacao")
                        .HasForeignKey("TutoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClyvoDayApiDocker.Models.Tutores", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutoresId1");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("ClyvoDayApiDocker.Models.EventoCuidado", b =>
                {
                    b.HasOne("ClyvoDayApiDocker.Models.AnimalEstimacao", "AnimalEstimacao")
                        .WithMany()
                        .HasForeignKey("AnimalEstimacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalEstimacao");
                });

            modelBuilder.Entity("ClyvoDayApiDocker.Models.MonitoramentoAnimal", b =>
                {
                    b.HasOne("ClyvoDayApiDocker.Models.AnimalEstimacao", "AnimalEstimacao")
                        .WithMany()
                        .HasForeignKey("AnimalEstimacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalEstimacao");
                });

            modelBuilder.Entity("ClyvoDayApiDocker.Models.Veterinario", b =>
                {
                    b.HasOne("ClyvoDayApiDocker.Models.Clinica", "Clinica")
                        .WithMany("Veterinarios")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("ClyvoDayApiDocker.Models.Clinica", b =>
                {
                    b.Navigation("Veterinarios");
                });

            modelBuilder.Entity("ClyvoDayApiDocker.Models.Tutores", b =>
                {
                    b.Navigation("AnimaisEstimacao");
                });
#pragma warning restore 612, 618
        }
    }
}
